name: task-tracker
region: nyc
services:
  - name: web
    git:
      repo_clone_url: https://github.com/sai2611990/task-tracker.git
      branch: main
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3000
    build_args:
      - name: NEXT_PUBLIC_SUPABASE_URL
        value: "https://zlgxekqrlgblgsquvvek.supabase.co"
      - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "sb_publishable_jrRdmZ8xkErc3bNqO-EDVQ_xCPd2l6V"
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_TIME
        value: "https://zlgxekqrlgblgsquvvek.supabase.co"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_TIME
        value: "sb_publishable_jrRdmZ8xkErc3bNqO-EDVQ_xCPd2l6V"
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        value: "sb_secret_FS7xO1kdSmHDGe8qUPSk-w_55kphQwW"
